version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: survey_feedback_app_development
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  

  web:
    build: .
    command: sh -c "bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
